# AUTHENTICATE USER 
POST http://localhost:3333/authenticate
Content-Type: application/json

{
    "email": "leonardohenriquesoarasalvez784@gmail.com"
}

###

# CREATE CUSTOMER 
POST http://localhost:3333/customer
Content-Type: application/json

{
    "name": "Leonardo Henrique Soares Alvez",
    "phone": "28776541534",
    "email": "leonardohenriquesoarasalvez784@gmail.com"
}

###

#REGISTER RESTAURANT

POST http://localhost:3333/restaurants
Content-Type: application/json

{
    "restaurantName": "Casa do Hamburguer",
    "description": "hamburguers artesanais de vários tipos",
    "managerName": "Leonardo Henrique Soares Alvez",
    "phone": "28776549534",
    "email": "casadohamburguer@gmail.com"
}

###

# CREATE ORDER

POST http://localhost:3333/restaurants/m2haayvpavuzf16rbjc5o5on/orders
Content-Type: application/json
Cookie: auth=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqeGVlM3FuaWg3NGdlazU3cXdzYTVqOTciLCJyZXN0YXVyYW50SWQiOiJtMmhhYXl2cGF2dXpmMTZyYmpjNW81b24ifQ.iK1BfJHpRMoQFSxct4escmH06NWR8L10ZZov8Tr_DXg

{
    "items": [
        {
            "productId": "f9bf12m5jo69l2aqodxejm9z",
            "quantity": 2
        },
          {
            "productId": "gayybvrft98n0ff7emm4bhy0",
            "quantity": 3
        }
    ]
}

###

# GET CUSTOMERS 
GET http://localhost:3333/

###


# GET RESTAURANTS 
GET http://localhost:3333/restaurants

###


# LOGOUT CUSTOMER 
GET http://localhost:3333/sign-out
